version: "3.8"
services: 
  redis:
    image: redis:latest
    restart: always
    ports: 
      - "6379:6379"

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mypass

  backend_rds:
    build: ./backend_rds
    ports: 
       - "8000:8000"
    environment:
      DB_NAME: 'postgres'
      DB_USER: 'postgres'
      DB_PASSWORD: 'mypass'
      DB_HOST: 'db'
      DB_PORT: 5432
      CORS_ALLOWED_ORIGINS: 'http://localhost:3000' 
    depends_on:
        - db

  backend_redis:
    build: ./backend_redis
    ports: 
       - "8001:8001"
    environment:
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_PASSWORD: ""
      CORS_ALLOWED_ORIGINS: 'http://localhost:3000'
    depends_on:
        - redis

  frontend: 
    build: ./frontend
    ports:
      - "3000:80"